### ISSUE TITLE
Invisible in Resource Selection

### ISSUE THREAD

**Issue by DarkBreaker09** [John-Smith-Modded/JSTR-Modded-1.10.x#10]
Hey there.
I saw this Pack by an Friend and found it great,
After I downloaded it here I Placed the .zip file in my Resource folder form MC 1,10,2.
But after starting MC I cant see it under the Settings-Resource Pack.

I called my Friend where i did see this Pack but he wasnt able to help me.
He said he just downloaded it and place it where it should be (same that i did).
I hope you Guys can give me an helping hand on this.

What i did try ;
Rename the Pack to JSTR_Modded_1.10.x_master.zip (original was JSTR-Modded-1.10.x-master)
Rename the Pack to JSTR-Modded-1.10-master (did remember to an Bug where i couldnt use packs with an x in the name)
Redownloaded the Pack

**Comment by damonmensch** [comment]
Hello @DarkBreaker09 are you downloading the pack from GitHub here under it's download link?

You should be downloading it from Curse's website here: https://mods.curse.com/texture-packs/minecraft/223328-john-smith-legacy-modded

The zip on GitHub isn't properly formatted for it to be recognized by Minecraft. The ones on Curse are.

@Oddface & @artdude543 the 1.10 repo isn't being updated to Curse for some reason.

**Comment by Oddface** [comment]
The 1.10 version is being published on Curse now, so I'm closing this.
