### ISSUE TITLE
Porting Tinker's textures

### ISSUE THREAD

**Issue by katycat5e** [John-Smith-Modded/JSTR-Modded-1.10.x#15]
I created this issue to ask about the status of updates to the pack, as well as check what the policy was for modifying textures from the older JSTR versions (specifically 1.7.10) for use in 1.10 and possibly 1.12 if they'll work. The Tinker's Construct GUIs were changed since 1.7.10 which is presumably why the textures were left out of this repo. I don't really have great skill at creating new textures but I have had some success with doing "pixel surgery" on the existing GUIs and utilizing the JS Vanilla textures.

![5refglo 1](https://user-images.githubusercontent.com/11540268/47034168-95711e80-d144-11e8-96fb-5114731e7174.png)

**Comment by lesdmark** [comment]
As far as porting textures to new versions, that is perfectly acceptable to do as long as they are the same. Feel free to do so and most of us have to practice our pixel surgery as well to get the textures updated to newer versions so no worries there! Just submit a pull request when you have something you wanted added and someone will take a look and make sure it is ok and get it integrated.
