### ISSUE TITLE
Immerse Engineering Model textures  need a little tweaking. 

### ISSUE THREAD

**Issue by sigurdtheone** [John-Smith-Modded/JSTR-Modded-1.10.x#3]
A couple of textures are currently not being wrapped on models properly.

Wooden Poles and LV wire connectors, have no idea how to edit these tho

**Comment by sigurdtheone** [comment]
This also applies to the Excavator

**Comment by ghost** [comment]
A number of models appear to have been re-wrapped, while other textures were renamed. I've fixed the misnamed ones and moved around the bits on the texture sheets for the ones that changed, though I could have accidentally missed some. There are a whole bunch of them that had to change, so here's a zip file of my copy—I'm not sure how else to reasonably supply them.
[Immersive_Engineering.zip](https://github.com/John-Smith-Modded/JSTR-Modded-1.10.x/files/1067966/Immersive_Engineering.zip)

**Comment by Oddface** [comment]
https://github.com/John-Smith-Modded/JSTR-Modded-1.10.x/issues/8
