### ISSUE TITLE
cobblestone stairs not connecting upside down

### ISSUE THREAD

**Issue by pjcminecraft** [John-Smith-Modded/JSTR-Modded-1.10.x#7]
i changed my texture to JSTR_MODDED_UNIVERSAL and noticed that cobblestone 
and stonebrick stairs will not connect upside down around corners ..it unconnected all the stairs i had in place... I also noticed that when placeing the cobblestone stairs you can see the pink and black box on the bottom while it is in hand

if you have any questions please contact me at pjcminecraft@yahoo.com

Thanks

**Comment by damonmensch** [comment]
Could you please show us a screenshot of this occurring so we can investigate it further?

**Comment by Oddface** [comment]
Just made a fix. Thank you for the bug report, and sorry for not fixing it earlier.
